version: '3.9'

services:
  backend:
    build: ./backend
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    environment:
      - DEBUG=1
      - DATABASE_URL=postgres://url:url@db:5432/postgres
      - CELERY_BROKER_URL=redis://redis:6379/0

  frontend:
    build: ./frontend
    ports:
      - "5173:80"
    depends_on:
      - backend

  db:
    image: postgres:16
    environment:
      - POSTGRES_USER=url
      - POSTGRES_PASSWORD=url
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7

  celery:
    build: ./backend
    command: celery -A url worker --loglevel=info
    volumes:
      - ./backend:/app
    depends_on:
      - backend
      - redis

  celery_beat:
    build: ./backend
    command: celery -A url beat --loglevel=info
    volumes:
      - ./backend:/app
    depends_on:
      - backend
      - redis

volumes:
  pgdata:

